# Generated by Django 5.2.5 on 2025-09-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMSApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authmodel',
            name='username',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
