# Generated by Django 5.2.5 on 2025-09-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMSApp', '0002_alter_loan_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(default='pending', max_length=40),
        ),
    ]
