# Generated by Django 5.2.5 on 2025-09-19 16:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMSApp', '0004_repayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10)),
                ('date_sent', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
