# Generated by Django 5.2.5 on 2025-09-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMSApp', '0005_communication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='channel',
            field=models.CharField(blank=True, choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10),
        ),
        migrations.AlterField(
            model_name='communication',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='communication',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
