# Generated by Django 5.2.5 on 2025-09-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMSApp', '0006_alter_communication_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
